---
- name: Get Karbon batch
  uri:
    url: https://{{ inventory_hostname }}:7050/prism/api/nutanix/v3/batch
    method: POST
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Cookie: "{{ login.set_cookie }}"
    validate_certs: no
    return_content: yes
    status_code: 200
    body_format: json
    body: "{{ lookup('file','batch_body.j2') | from_yaml }}"
  register: karbon_batch