- name: Karbon Create cluster
  hosts: all
  gather_facts: no
  connection: local
  roles:
    - ../pipoe2h.ntnx_pc-login
    - ../pipoe2h.ntnx_karbon-batch
    - ../pipoe2h.ntnx_karbon-create_cluster
    - ../pipoe2h.ntnx_pc-task
    - ../pipoe2h.ntnx_karbon-get_kubeconfig